AppCrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.conf import settings
import calendar

urlpatterns = [
    path('portalAdmin/', admin.site.urls),
    #path('default/', default, )
    path('', include('core.urls', namespace='core')),
    path('clientes/', include('contacts.urls', namespace='contacts')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contacts/urls.py
from django.urls import path

from .views import *

app_name='contacts'

urlpatterns = [
    path('', listar_contatos, name='listar_contatos'), 
    path('novo_contato/', novo_contato, name='novo_contato'), 
]

core/urls.py
from django.urls import path

from .views import *

app_name='core'
urlpatterns = [
    path('', index, name='index'),  
]

calendarApp/models.py
from django.db import models

# Create your models here.

contacts/models.py
from django.db import models
from core.models import Base

from django.db.models import signals
#from django.template.defaultfilters import slugify

# Create your models here.


#Definição de informações geográficas

class Country(Base):
    name = models.CharField('País', max_length=100)
    DDI_Code = models.CharField('DDI', max_length=5)

    class Meta:
        verbose_name = 'País'
        verbose_name_plural = 'Paises'

class State(Base):
    name = models.CharField('Estado', max_length=100)
    id_country = models.ForeignKey(Country, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Estado'
        verbose_name_plural = 'Estados'

class City(Base):
    name = models.CharField('Cidade', max_length=255)
    id_state = models.ForeignKey(State, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Cidade'
        verbose_name_plural = 'Cidades'

class PostalCode(Base):
    postal_code = models.CharField('Código postal', max_length=30)
    id_city = models.ForeignKey(City, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'CEP'
        verbose_name_plural = 'CEPs'

#Definição de tipos de pessoa física e jurídica (CPF e CNPJ ou outros documentos, se considerar outros países)
class TaxType(Base):
    name = models.CharField('Documento Fiscal', max_length=40)
    character_limit = models.IntegerField('Limite de caracteres', default=20)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Documento Fiscal'
        verbose_name_plural = 'Documentos Fiscais'

#Definição básica de pessoa
class Person(Base):
    tax_id = models.CharField('ID Fiscal', max_length=20)    
    tax_type = models.ForeignKey(TaxType, on_delete=models.PROTECT)

    def __str__(self):
        return self.tax_id
    
    class Meta:
        verbose_name = 'Pessoa'
        verbose_name_plural = 'Pessoas'

class NaturalPerson(Person): #Pessoa física
    first_name = models.CharField('Nome', max_length=100)
    last_name = models.CharField('Sobrenome', max_length=255)
    birth_date = models.DateField('Data de Nascimento')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    
    class Meta:
        verbose_name = 'Pessoa física'
        verbose_name_plural = 'Pessoas físicas'
                                  
class LegalPerson(Person): #Pessoa jurídica
    company_name = models.CharField('Nome da empresa', max_length=255)
    company_creation_date = models.DateField('Data de Criação da Companhia')
    #industry

    class Meta:
        verbose_name = 'Pessoa jurídica'
        verbose_name_plural = 'Pessoas jurídicas'


class UseType(Base):
    name = models.CharField('Tipo de uso', max_length=30)

    class Meta:
        verbose_name = 'Tipo'
        verbose_name_plural = 'Tipos'


#Definição de e-mail
class Email(Base):
    id_person = models.ForeignKey(Person, on_delete=models.CASCADE)
    email = models.EmailField('Email', max_length=128)
    use_type = models.ForeignKey(UseType, on_delete=models.PROTECT)
    is_main_email = models.BooleanField('Email principal?', default=False)

    class Meta:
        verbose_name = 'Email'
        verbose_name_plural = 'Emails'

#Definição de telefone
class Telephone(Base):
    id_person = models.ForeignKey(Person, on_delete=models.CASCADE)
    phone_number = models.CharField('Número de telefone', max_length=50)
    id_DDI = models.ForeignKey(Country, on_delete=models.PROTECT)
    use_type = models.ForeignKey(UseType, on_delete=models.PROTECT)
    is_main_phone = models.BooleanField('Telefone principal?', default=False)

    class Meta:
        verbose_name = 'Telefone'
        verbose_name_plural = 'Telefones'

class Address(Base):
    id_person = models.ForeignKey(Person, on_delete=models.CASCADE)
    street_name = models.CharField('Rua', max_length=120)
    number = models.CharField('Número', max_length=5)
    addon_address = models.CharField('Complemento', max_length=200)
    id_cep = models.ForeignKey(PostalCode, on_delete=models.PROTECT)
    use_type = models.ForeignKey(UseType, on_delete=models.PROTECT)
    is_main_address = models.BooleanField('Endereço principal?', default=False)

    class Meta:
        verbose_name = 'Endereço'
        verbose_name_plural = 'Endereços'

core/models.py
from django.db import models
from django.db.models import signals
from django.template.defaultfilters import slugify

# Create your models here.
class Base(models.Model):
    created_at = models.DateField('Data de Criação', auto_now_add=True)
    modified_at = models.DateField('Data de Modificação', auto_now=True)
    is_active = models.BooleanField('Ativo?', default=True)

    class Meta:
        abstract = True

contacts/forms.py
from django import forms 
from django.core.mail.message import EmailMessage

from .models import *

class NovoContatoForm(forms.ModelForm):
    class Meta:
        model = NaturalPerson
        fields = ['first_name', 'last_name', 'birth_date', 'tax_type', 'tax_id']

calendarApp/views.py
from django.shortcuts import render

# Create your views here.

contacts/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib import messages

from django.http import HttpResponse
from django.template import loader

from .models import *
from .forms import *

from django.apps import apps

__app_config = apps.get_app_config('contacts')
__app_name = __app_config.name

# Create your views here.

def listar_contatos(request):
    context = {
        'curso': 'Django Framework',
        'outro': 'Django é massa!',
    }
    return render(request, f'{__app_name}/listar_contatos.html', context)

def novo_contato(request):
    if str(request.user) == 'POST':
        return redirect('listar_contatos')
    
    if str(request.method) == 'POST':
        form = NovoContatoForm(request.POST, request.FILES)

        if form.is_valid():
            contato = form.save(commit=True)
            print(f'Nome: {contato.first_name}')
            print(f'Sobrenome: {contato.last_name}')
            print(f'Data de Nascimento: {contato.birth_date}')
            print(f'Documento Fiscal: {contato.tax_type}')
            print(f'ID Fiscal: {contato.tax_id}')
                
            messages.success(request, f'{__app_name}/Cliente salvo com sucesso')
            form = NovoContatoForm()
        else:
            messages.error(request, f'{__app_name}/Erro ao salvar cliente')

    else:
        form = NovoContatoForm()
        
    context = {
        'form': form
    }

    return render(request, f'{__app_name}/novo_contato.html', context)

core/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from django.http import HttpResponse
from django.template import loader

from .models import *
from contacts import *

from django.apps import apps


__app_config = apps.get_app_config('core')
__app_name = __app_config.name

# Create your views here.
def index(request):
    context = {
        'curso': 'Vários clientes para você',
        'outro': 'Com o nosso app!',
    }
    return render(request, f'{__app_name}/index.html', context)

AppCrm/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Página inicial - Template</title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        
    </head>
    <body>
        <header>
            <div class="header">
                <div class="header-content">
                    <div class="logo">
                        {logo}
                    </div>
                    <div class="title">
                        <p>Título</p>
                    </div>
                    
                    <div class="menu">
                        <a href="" class="btn btn-tertiary"><span>Página inicial</span></a>
                        <a href="" class="btn btn-tertiary"><span>Funcionalidades</span></a>
                        <a href="" class="btn btn-tertiary"><span>Planos & Preços</span></a>
                        <a href="" class="btn btn-tertiary"><span>Sobre nós</span></a>
                        <a href="" class="btn btn-tertiary"><span>Suporte</span></a>
                        <a href="" class="btn btn-secondary"><span>Logar</span></a>
                        <a href="" class="btn btn-primary"><span>Assine um plano</span></a>
                    </div>
                </div>
            </div>
        </header>
        {% block content %}
        {% endblock %}
        <footer>
            <h5>Rodapé</h5>
        </footer>
    </body>
</html>

AppCrm/templates/base_layout.html
<!--{% load static %}-->
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Página inicial - Template</title>
        <!-- <link rel="stylesheet" href="{% static 'css/main.css' %}"> -->
        <link rel="stylesheet" href="../static/css/AppCrm/main.css">
    </head>
    <body>
        <header>
            <div class="header">
                <div class="header-content">
                    <div class="logo">
                        {logo}
                    </div>
                    <div class="title">
                        <p>Título</p>
                    </div>
                    
                    <div class="menu">
                        <a href="" class="btn btn-tertiary"><span>Página inicial</span></a>
                        <a href="" class="btn btn-tertiary"><span>Funcionalidades</span></a>
                        <a href="" class="btn btn-tertiary"><span>Planos & Preços</span></a>
                        <a href="" class="btn btn-tertiary"><span>Sobre nós</span></a>
                        <a href="" class="btn btn-tertiary"><span>Suporte</span></a>
                        <a href="" class="btn btn-secondary"><span>Logar</span></a>
                        <a href="" class="btn btn-primary"><span>Assine um plano</span></a>
                    </div>
                </div>
            </div>
        </header>

    <div class="content">
        adasdasdasdsa
    </div>

    <footer>
        <div class="footer">

        </div>
    </footer>
    </body>
</html>

AppCrm/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Página inicial - Template</title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        
    </head>
    <body>
        <header>
            <div class="header">
                <div class="header-content">
                    <div class="logo">
                        {logo}
                    </div>
                    <div class="title">
                        <p>Título</p>
                    </div>
                    
                    <div class="menu">
                        <a href="" class="btn btn-tertiary"><span>Página inicial</span></a>
                        <a href="" class="btn btn-tertiary"><span>Funcionalidades</span></a>
                        <a href="" class="btn btn-tertiary"><span>Planos & Preços</span></a>
                        <a href="" class="btn btn-tertiary"><span>Sobre nós</span></a>
                        <a href="" class="btn btn-tertiary"><span>Suporte</span></a>
                        <a href="" class="btn btn-secondary"><span>Logar</span></a>
                        <a href="" class="btn btn-primary"><span>Assine um plano</span></a>
                    </div>
                </div>
            </div>
        </header>
        {% block content %}
        {% endblock %}
    </body>
</html>

AppCrm/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Página inicial - Template</title>
    </head>
    <body>
        <p>{{ curso }}</p>
        <p>{{ outro }}</p>
    </body>
</html>

contacts/templates/contacts/listar_contatos.html
{% extends 'AppCrm/templates/base.html' %}
{% load static %}
{% block content %}
<content>
    Tela para apresentar os clientes registrados para aquele usuário
            <a href="{% url 'contacts:novo_contato' %}">Novo contato</a>
</content>
{% endblock %}

contacts/templates/contacts/novo_contato.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <!--Mudar posteriormente para o título ser o nome do formulário ou ação a ser executada pelo usuário-->
        <!--Exemplo: cadastro de novo cliente, de novo endereço, rastreamento entre outras opções -->
        <title>Novo cliente</title>
        {% bootstrap_css %}
    </head>
    <body>
        <div class="container">
            <h1>Novo cliente</h1>
            <form action="{% url 'contacts:novo_contato' %}" method="post" class="form" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                
                {% bootstrap_form form %}
                
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Enviar</button>
                {% endbuttons %}
            </form>
        </div>
        
    </body>
    
    {% bootstrap_javascript jquery='full' %}
</html>

core/templates/core/index copy.html
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Página inicial - Core</title>
    </head>
    <body>
        <p>{{ curso }}</p>
        <p>{{ outro }}</p>
        <a href="{% url 'contacts:listar_contatos' %}">Clientes</a>
    </body>
</html>

core/templates/core/index.html
{% extends 'AppCrm/templates/base.html' %}
{% load static %}
{% block content %}
    <body>
        <p>{{ curso }}</p>
        <p>{{ outro }}</p>
        <a href="{% url 'contacts:listar_contatos' %}">Clientes</a>
    </body>
{% endblock %}